name = "foobar-app"
main = "src/index.tsx"
compatibility_date = "2024-09-23"

[[kv_namespaces]]
binding = "FOOBAR_USERS"
id = "00000000000000000000000000000000"
preview_id = "11111111111111111111111111111111"

[vars]
BROKER_URL = "http://localhost:8789"
CSS_BASE_URL = "http://localhost:3000"
OAUTH_ADMIN_URL = "http://localhost:8799/admin"
# CSS_PROVISION_URL = "http://localhost:3000/.internal/provision"

[observability]
enabled = true

[dev]
port = 8791
local_protocol = "http"
