name = "solid-broker"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[[kv_namespaces]]
binding = "BROKER_KV"
id = "00000000000000000000000000000000"
preview_id = "11111111111111111111111111111111"

[vars]
# External issuer URL of this broker (must match how clients access it)
BROKER_ISSUER = "http://localhost:8789"
# WebID strategy:
# - Set to "self" to mint: <BROKER_ISSUER>/webid/<sub>#me
# - Or set a hostname to mint: https://<WEBID_HOST>/<sub><WEBID_PATH><WEBID_FRAGMENT>
WEBID_HOST = "self"
WEBID_PATH = ""
WEBID_FRAGMENT = "#me"
# Default TTL for tokens
TOKEN_TTL_SECONDS = 300
# Backing provider config (example: local cloudflare-oauth-server)
BACKING_ISSUER = "http://localhost:8799"
BACKING_CLIENT_ID = "oftL3RsnoPgaO5Lz"
BACKING_AUTH_PATH = "/authorize"
BACKING_TOKEN_PATH = "/oauth/token"
# Optional userinfo path if backing provider is OAuth2-only
# BACKING_USERINFO_PATH = "/api/whoami"
JWT_KID = "broker-key-1"

[observability]
enabled = true

[dev]
port = 8789
local_protocol = "http"
